title = "Test Site"

[menu]
  # main menu
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/home"
    weight = 10

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages"
    weight = 30

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio"
    weight = 40

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 50