backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"
collections:
  - name: "Homepage"
    label: "Homepage"
    files:
      - file: "content/section2.md"
        label: "Section 2"
        name: "section 2"
        fields:
          - label: "Section 2 Subtitle"
            name: "section2_subtitle"
            widget: "string"
          - label: "Section 2 Title"
            name: "section2_title"
            widget: "string"
          - label: "Section 2 Description"
            name: "section2_desc"
            widget: "string"
          - label: "Section 2 Button Text"
            name: "section2_btn_txt"
            widget: "string"
          - label: "Section 2 Image ( 800 x 800 )"
            name: "section2_image"
            widget: "image"
          - label: "Section 3 Subtitle"
            name: "section3_subtitle"
            widget: "string"
      - file: "content/section3.md"
        label: "Section 3"
        name: "section 3"
        fields:
          - label: "Section 3 Subtitle"
            name: "section3_subtitle"
            widget: "string"
          - label: "Section 3 Title"
            name: "section3_title"
            widget: "string"
          - label: "Section 3 Description"
            name: "section3_desc"
            widget: "string"
          - label: "Section 3 Cards"
            name: "section3_cards"
            widget: "list"
            fields:
              - label: "Icon Image"
                name: "icon_img"
                widget: "image"
              - label: "Icon Title"
                name: "title"
                widget: "string"
              - label: "Icon Description"
                name: "description"
                widget: "string"
      - file: "content/section4.md"
        label: "Section 4"
        name: "section 4"
        fields:
          - label: "Section 4 Image ( 800 x 800 )"
            name: "section4_image"
            widget: "image"
          - label: "Section 4 Subtitle"
            name: "section4_subtitle"
            widget: "string"
          - label: "Section 4 Title"
            name: "section4_title"
            widget: "string"
          - label: "Section 4 Dropdowns"
            name: "section4_dropdowns"
            widget: "list"
            fields:
              - label: "Dropdown Title"
                name: "title"
                widget: "string"
              - label: "Dropdown Description"
                name: "description"
                widget: "string"
      - file: "content/section5.md"
        label: "Section 5"
        name: "section 5"
        fields:
          - label: "Section 5 Subtitle"
            name: "section5_subtitle"
            widget: "string"
          - label: "Section 5 Title"
            name: "section5_title"
            widget: "string"
          - label: "Section 5 Description"
            name: "section5_desc"
            widget: "string"
          - label: "Section 5 Working Days"
            name: "section5_working_days"
            widget: "list"
            fields:
              - label: "Day"
                name: "day"
                widget: "string"
              - label: "Hours"
                name: "hours"
                widget: "string"
      - file: "content/section6.md"
        label: "Section 6"
        name: "section 6"
        fields:
          - label: "Section 6 Image ( 1920 x 1080 )"
            name: "section6_image"
            widget: "image"
      - file: "content/section7.md"
        label: "Section 7"
        name: "section 7"
        fields:
          - label: "Section 7 Subtitle"
            name: "section7_subtitle"
            widget: "string"
          - label: "Section 7 Title"
            name: "section7_title"
            widget: "string"
          - label: "Section 7 Prices - LEFT SIDE"
            name: "section7_treatments_left"
            widget: "list"
            fields:
              - label: "Service Title"
                name: "title"
                widget: "string"
              - label: "Price"
                name: "price"
                widget: "string"
              - label: "Duration"
                name: "duration"
                widget: "string"
          - label: "Section 7 Prices - RIGHT SIDE"
            name: "section7_treatments_right"
            widget: "list"
            fields:
              - label: "Service Title"
                name: "title"
                widget: "string"
              - label: "Price"
                name: "price"
                widget: "string"
              - label: "Duration"
                name: "duration"
                widget: "string"
          - label: "Section 7 Button Text"
            name: "section7_button_txt"
            widget: "string"
          - label: "Section 7 Button Link (URL)"
            name: "section7_button_href"
            widget: "string"