backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"
collections:
  - name: "Sections"
    label: "Sections"
    files:
      - file: "content/_index_s2.md"
        label: "Section 2"
        name: "section_2"
        fields:
          - { label: "Section 2 Subtitle", name: "section2_subtitle", widget: "string" }
          - { label: "Section 2 Title", name: "section2_title", widget: "string" }
          - { label: "Section 2 Description", name: "section2_desc", widget: "string" }
          - { label: "Section 2 Button Text", name: "section2_btn_txt", widget: "string" }
          - { label: "Section 2 Image ( 800 x 800 )", name: "section2_image", widget: "image" }