backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"
collections:
  - name: "Sections"
    label: "Sections"
    files:
      - file: "content/_index_s2.md"
        label: "Section 2"
        name: "section_2"
        fields:
          - label: "Section 2 Subtitle"
            name: "section2_subtitle"
            widget: "string"
            required: true
          - label: "Section 2 Title"
            name: "section2_title"
            widget: "string"
            required: true
          - label: "Section 2 Description"
            name: "section2_desc"
            widget: "string"
            required: true
          - label: "Section 2 Button Text"
            name: "section2_btn_txt"
            widget: "string"
            required: true
          - label: "Section 2 Image ( 800 x 800 )"
            name: "section2_image"
            widget: "image"
            required: true
      - file: "content/_index_s3.md"
        label: "Section 3"
        name: "section_3"
        fields:
          - label: "Section 3 Subtitle"
            name: "section3_subtitle"
            widget: "string"
            required: true
          - label: "Section 3 Title"
            name: "section3_title"
            widget: "string"
            required: true
          - label: "Section 3 Description"
            name: "section3_desc"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 1 - Image ( 80 x 80 )"
            name: "section3_icon1_img"
            widget: "image"
            required: true
          - label: "Section 3 - Icon 1 - Title"
            name: "section3_icon1_title"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 1 - Description"
            name: "section3_icon1_desc"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 2 - Image ( 80 x 80 )"
            name: "section3_icon2_img"
            widget: "image"
            required: true
          - label: "Section 3 - Icon 2 - Title"
            name: "section3_icon2_title"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 2 - Description"
            name: "section3_icon2_desc"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 3 - Image ( 80 x 80 )"
            name: "section3_icon3_img"
            widget: "image"
            required: true
          - label: "Section 3 - Icon 3 - Title"
            name: "section3_icon3_title"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 3 - Description"
            name: "section3_icon3_desc"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 4 - Image ( 80 x 80 )"
            name: "section3_icon4_img"
            widget: "image"
            required: true
          - label: "Section 3 - Icon 4 - Title"
            name: "section3_icon4_title"
            widget: "string"
            required: true
          - label: "Section 3 - Icon 4 - Description"
            name: "section3_icon4_desc"
            widget: "string"
            required: true
      - file: "content/_index_s4.md"
        label: "Section 4"
        name: "section_4"
        fields:
          - label: "Section 4 Image ( 800 x 800 )"
            name: "section4_image"
            widget: "image"
            required: true
          - label: "Section 4 Subtitle"
            name: "section4_subtitle"
            widget: "string"
            required: true
          - label: "Section 4 Title"
            name: "section4_title"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 1 - Title"
            name: "section4_dropdown1_title"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 1 - Description"
            name: "section4_dropdown1_desc"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 2 - Title"
            name: "section4_dropdown2_title"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 2 - Description"
            name: "section4_dropdown2_desc"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 3 - Title"
            name: "section4_dropdown3_title"
            widget: "string"
            required: true
          - label: "Section 4 - Dropdown 3 - Description"
            name: "section4_dropdown3_desc"
            widget: "string"
            required: true
      - file: "content/_index_s5.md"
        label: "Section 5"
        name: "section_5"
        fields:
          - label: "Section 5 Subtitle"
            name: "section5_subtitle"
            widget: "string"
            required: true
          - label: "Section 5 Title"
            name: "section5_title"
            widget: "string"
            required: true
          - label: "Section 5 Description"
            name: "section5_desc"
            widget: "string"
            required: true
          - label: "Working Days"
            name: "working_days"
            widget: "list"
            fields:
              - label: "Day"
                name: "day"
                widget: "string"
              - label: "Hours"
                name: "hours"
                widget: "string"
            required: true
